apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: staging
data:
  ENVIRONMENT: staging
  LOG_LEVEL: DEBUG
  MODEL_CACHE_SIZE: "256MB"
  MAX_WORKERS: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
