apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-recommender-api
  template:
    metadata:
      labels:
        app: movie-recommender-api
    spec:
      containers:
      - name: api
        image: movie-recommender-api:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: secret-key
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
